### PR TITLE
Improvements to the bot while the maintainer is away

### PR DESCRIPTION
**Pull request by xBelladonna**
Hello! I honestly wasn't sure whether to open this PR or not, but I have made a number of changes on top of your already improved (not to mention fixed and updated) fork. All changes are listed in commit history, and summarized below. These changes are an active work in progress, and I am working on fleshing out some of the features I've added to make them more versatile and robust. Please let me know if you want to discuss anything, or if you'd rather not merge and want to figure out another way forward :3

Summary of feature changes:
- Add docker configuration
- Voice calls
  - Add configuration to enable/disable speaking replies and posting replies in the voice text channel
  - Clean text to extract only dialogue for TTS
- Make response chance table configurable, along with interrobang bonus
- Add configuration to image generation module to enable bot to generate self-portrait
- Vision API
  - Downsample image attachments if bigger than certain size - helps fit base64 into model context
  - Enable recognition of images at URLs
  - Include message author in notification to AI

DISCLAIMER: extreme sleep deprivation was experienced while working on this code. While every attempt has been made to adequately test and ensure that the software functions correctly, there may still be some bugs that were missed. Please ensure to review and test before deploying in production!

### CODE REVIEW

**Comment by jmoney7823956789378** [comment]
Did you do all this in just the past day? Impressive. I have a few more pending commits I'm about to push and I'll see if it still merges. 👍

**Comment by xBelladonna** [comment]
Thanks! I have been messing with this for a couple days but all those commits were done so close together because I was irresponsible and didn't commit changes properly as I was going. No worries if there's merge conflicts, I can sort them out on my end and force push.

**Comment by xBelladonna** [comment]
There we go, ~~roughly shoved~~ gently shipped a new head to the branch and it should merge now. Also added some more commits, both bugfixes and features, all neatly summarized in the commit messages. Please let me know if you want to review/discuss/change anything!

I also plan later on to add a feature that collects the display names of everyone in the current channel, and for each successive prompt of the model, adds them all as stopping strings to the actual generation task, which will cause the model to immediately stop generation instead of having to filter out bad lines. Only issue is how that might scale (or not, as it were), which I'm trying to figure out.

**Comment by jmoney7823956789378** [comment]
This is great! A much better job than a noob like me, and way better commit management LOL.
However, just a small thing about the vision changes:
https://github.com/jmoney7823956789378/oobabot/pull/2/commits/eb92058c160fba673a8f7f4fbbe62de8f24d8b2c#diff-d2fa8e09281ebfeb0818c3c7a8da7d2c7aa2b0bd7e4b12e38280d27a3c03c6f8R188
```
                if should_respond:
                    urls = self.url_extractor.findall(raw_message.content)
                    if urls:
                        for url in urls:
                            r = requests.head(url)
```
This section may need to be an optional setting, as having the bot grab headers of any URLs sent by a user can lead to potential leakage of the bot host's IP.
Everything else looks good after a quick lookover, and I'll take a closer look when I'm actually free.
I'd really like to figure a way to rework the voice section to use more up-to-date TTS/STT solutions, eventually.

**Comment by xBelladonna** [comment]
There you go, it's now configurable and false by default!

**Comment by xBelladonna** [comment]
I'm very interested in getting up to date TTS/STT for voice calls, and it's actually one of my most wanted goals. I'm working on coming up with a decent extensible architecture to make integration of different modules easy, and plan to integrate XTTS along with RVC first. Probably the most useful two additions for making the bot sound like anything you want with very good prosody that even competes with Elevenlabs. Only issue is you need a very good GPU to run LLM + STT + TTS + RVC for approx. realtime inference, I have a RTX 4090 and even then she still struggles from time to time, though I am also running Stable Diffusion on top of all that. The idea of extensibility is to keep the ability to remain flexible for systems with limited resources.

**Comment by jmoney7823956789378** [comment]
> I'm working on coming up with a decent extensible architecture to make integration of different modules easy, and plan to integrate XTTS along with RVC first.

I have a semi-working solution working using (https://github.com/imayhaveborkedit/discord-ext-voice-recv) to actually fetch discord audio data, since the actual discord.py package doesn't really provide that functionality yet.
I have plans to use [faster-whisper](https://github.com/SYSTRAN/faster-whisper) + [RealtimeTTS](https://github.com/KoljaB/RealtimeTTS) or [edge-tts](https://github.com/rany2/edge-tts) and succeeded in making a very rudimentary implementation using these. My goal was minimizing latency between "End User Speaking" and "Begin Bot Speaking", but in my case I have a lot of compute available (2x 3090 + 4x A4000)...
I can upload my draft(s) and share them if you're interested.

**Review by jmoney7823956789378 — APPROVED** [review]
May consider splitting the user and AI prefix/suffix settings to allow for proper prompt templating later. Thanks!

**Comment by xBelladonna** [comment]
> > I'm working on coming up with a decent extensible architecture to make integration of different modules easy, and plan to integrate XTTS along with RVC first.
> 
> I have a semi-working solution working using (https://github.com/imayhaveborkedit/discord-ext-voice-recv) to actually fetch discord audio data, since the actual discord.py package doesn't really provide that functionality yet. I have plans to use [faster-whisper](https://github.com/SYSTRAN/faster-whisper) + [RealtimeTTS](https://github.com/KoljaB/RealtimeTTS) or [edge-tts](https://github.com/rany2/edge-tts) and succeeded in making a very rudimentary implementation using these. My goal was minimizing latency between "End User Speaking" and "Begin Bot Speaking", but in my case I have a lot of compute available (2x 3090 + 4x A4000)... I can upload my draft(s) and share them if you're interested.

@jmoney7823956789378 I'd be very interested in taking a look! That's some serious compute you have there!
Also... I just noticed I missed some things with the image detection regexes, so I'll open another PR to fix that.

**Comment by jmoney7823956789378** [comment]
@xBelladonna Sorry to hit you up on this older PR, but I've been doing some prompt testing (via editing the prompt_generator.py directly) and found that we may need to utilize separate "prompt prefixes" for users and the bot, as some prompt formats will use a different one for both. For example, ChatML format is as so:
```
<|im_start|>system
(systemprompt)<|im_end|>
<|im_start|>user [user1]: example message <|im_end|>
<|im_start|>assistant [botname]: example response <|im_end|>
```
`<|im_end|>` does not need to be appended directly, but can be appended to the beginning of the previous response instead:
```
<|im_end|><|im_start|>user [user1]: followup message
<|im_start|>assistant [botname]: example message
```
Specifically for ChatML, I have seen good results when I remove the `user` or `assistant` portion, and left the raw tags beside the name:
```
<|im_start|>system
(systemprompt)<|im_end|>
<|im_start|>[user1]: example message <|im_end|>
<|im_start|>[botname]: example response <|im_end|>
```
Just and FYI since you already did most of the brainwork for prompt prefixes here, otherwise i might get to it eventually.

**Pull request merged**
